apiVersion: v1
kind: Service
metadata:
  name: guestbook-mongo
  #namespace: ns-cb-guestbook
  labels:
    app.kubernetes.io/name: guestbook-mongo
    app.kubernetes.io/component: guestbook-backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app.kubernetes.io/name: guestbook-mongo
    app.kubernetes.io/component: bguestbook-ackend