apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-mongo
  #namespace: ns-cb-guestbook
  labels:
    app.kubernetes.io/name: guestbook-mongo
    app.kubernetes.io/component: guestbook-backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: guestbook-mongo
      app.kubernetes.io/component: guestbook-backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestbook-mongo
        app.kubernetes.io/component: guestbook-backend
    spec:
      containers:
      - name: mongo
        image: mongo:4.2
        args:
          - --bind_ip
          - 0.0.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 27017